version: "3.7"
services:
  ####################################
  ######  SETUP FRONT CONTAINER ######
  #################################### 
  frontend:
      container_name: frontend
      ports:
        - '3000:3000'
      build:
        context: frontend
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/app
        - /app/node_modules
        - /app/.next

  #####################################
  ######  SETUP BACK CONTAINER   ######
  #####################################
  back:
      build: 
          context: ./back
      environment: 
          NODE_DEV: developement
      ports:
          - "5001:80"
      networks:
          - back
      depends_on:
          - db
      restart: always